### PR TITLE
Fluxstore Unexpected character

### PR DESCRIPTION
**Pull request by akifman**
Hello,
Fluxstore login page. 
I get an error on login page and payment page. How can I fix?
hata

### CODE REVIEW

**Comment by maheshts** [comment]
update fulutter sdk

**Comment by BriscoPeas93** [comment]
Hello Everyone is there any solution for this bug please?

**Comment by trunghieuvn** [comment]
Hi @BriscoPeas93  please follow https://support.inspireui.com/help-center 

Thank you

**Comment by BriscoPeas93** [comment]
hello Inspireui/Support
I have checked all the documents but I got nothing about that specific
error.

I really need help guys.

Thanks

**Comment by trunghieuvn** [comment]
Hi @BriscoPeas93 you can read policies please and can create ticket support if need any support https://inspireui.com/support-policies/

Thanks & Best Regards

**Pull request closed without merging**
